spring:
  application:
    name: goals
  datasource:
    url: jdbc:mysql://localhost:3306/finances
    username: root
    password: 994821@Nav
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8300

